// Third party scripts
/* Copyright (c) 2006 Brandon Aaron (http://brandonaaron.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php) 
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 *
 * $LastChangedDate: 2007-06-20 03:23:36 +0200 (Mi, 20 Jun 2007) $
 * $Rev: 2110 $
 *
 * Version 2.1
 */
(function(b){b.fn.bgIframe=b.fn.bgiframe=function(a){if(b.browser.msie&&parseInt(b.browser.version)<=6){a=b.extend({top:"auto",left:"auto",width:"auto",height:"auto",opacity:true,src:"javascript:false;"},a||{});var d=function(c){return c&&c.constructor==Number?c+"px":c},e='<iframe class="bgiframe"frameborder="0"tabindex="-1"src="'+a.src+'"style="display:block;position:absolute;z-index:-1;'+(a.opacity!==false?"filter:Alpha(Opacity='0');":"")+"top:"+(a.top=="auto"?"expression(((parseInt(this.parentNode.currentStyle.borderTopWidth)||0)*-1)+'px')":
	d(a.top))+";left:"+(a.left=="auto"?"expression(((parseInt(this.parentNode.currentStyle.borderLeftWidth)||0)*-1)+'px')":d(a.left))+";width:"+(a.width=="auto"?"expression(this.parentNode.offsetWidth+'px')":d(a.width))+";height:"+(a.height=="auto"?"expression(this.parentNode.offsetHeight+'px')":d(a.height))+';"/>';return this.each(function(){b("> iframe.bgiframe",this).length==0&&this.insertBefore(document.createElement(e),this.firstChild)})}return this};if(!b.browser.version)b.browser.version=navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)[1]})(jQuery);


(function(d){var r=d.fn.height,s=d.fn.width;d.fn.extend({height:function(){if(this[0]==window)return self.innerHeight||d.boxModel&&document.documentElement.clientHeight||document.body.clientHeight;if(this[0]==document)return Math.max(document.body.scrollHeight,document.body.offsetHeight);return r.apply(this,arguments)},width:function(){if(this[0]==window)return self.innerWidth||d.boxModel&&document.documentElement.clientWidth||document.body.clientWidth;if(this[0]==document)return Math.max(document.body.scrollWidth,
document.body.offsetWidth);return s.apply(this,arguments)},innerHeight:function(){return this[0]==window||this[0]==document?this.height():this.is(":visible")?this[0].offsetHeight-a(this,"borderTopWidth")-a(this,"borderBottomWidth"):this.height()+a(this,"paddingTop")+a(this,"paddingBottom")},innerWidth:function(){return this[0]==window||this[0]==document?this.width():this.is(":visible")?this[0].offsetWidth-a(this,"borderLeftWidth")-a(this,"borderRightWidth"):this.width()+a(this,"paddingLeft")+a(this,
"paddingRight")},outerHeight:function(){return this[0]==window||this[0]==document?this.height():this.is(":visible")?this[0].offsetHeight:this.height()+a(this,"borderTopWidth")+a(this,"borderBottomWidth")+a(this,"paddingTop")+a(this,"paddingBottom")},outerWidth:function(){return this[0]==window||this[0]==document?this.width():this.is(":visible")?this[0].offsetWidth:this.width()+a(this,"borderLeftWidth")+a(this,"borderRightWidth")+a(this,"paddingLeft")+a(this,"paddingRight")},scrollLeft:function(c){if(c!=
undefined)return this.each(function(){if(this==window||this==document)window.scrollTo(c,d(window).scrollTop());else this.scrollLeft=c});if(this[0]==window||this[0]==document)return self.pageXOffset||d.boxModel&&document.documentElement.scrollLeft||document.body.scrollLeft;return this[0].scrollLeft},scrollTop:function(c){if(c!=undefined)return this.each(function(){if(this==window||this==document)window.scrollTo(d(window).scrollLeft(),c);else this.scrollTop=c});if(this[0]==window||this[0]==document)return self.pageYOffset||
d.boxModel&&document.documentElement.scrollTop||document.body.scrollTop;return this[0].scrollTop},position:function(c,h){var b=this[0],f=b.parentNode,j=b.offsetParent;c=d.extend({margin:false,border:false,padding:false,scroll:false},c||{});var i=b.offsetLeft,e=b.offsetTop,g=b.scrollLeft,k=b.scrollTop;if(d.browser.mozilla||d.browser.msie){i+=a(b,"borderLeftWidth");e+=a(b,"borderTopWidth")}if(d.browser.mozilla){do{if(d.browser.mozilla&&f!=b&&d.css(f,"overflow")!="visible"){i+=a(f,"borderLeftWidth");
e+=a(f,"borderTopWidth")}if(f==j)break}while((f=f.parentNode)&&(f.tagName.toLowerCase()!="body"||f.tagName.toLowerCase()!="html"))}b=o(b,c,i,e,g,k);if(h){d.extend(h,b);return this}else return b},offset:function(c,h){var b=0,f=0,j=0,i=0,e=this[0],g=this[0],k,n=d.css(e,"position"),l=d.browser.mozilla,m=d.browser.msie,t=d.browser.safari;k=d.browser.opera;var p=false,q=false;c=d.extend({margin:true,border:false,padding:false,scroll:true,lite:false},c||{});if(c.lite)return this.offsetLite(c,h);if(e.tagName.toLowerCase()==
"body"){b=e.offsetLeft;f=e.offsetTop;if(l){b+=a(e,"marginLeft")+a(e,"borderLeftWidth")*2;f+=a(e,"marginTop")+a(e,"borderTopWidth")*2}else if(k){b+=a(e,"marginLeft");f+=a(e,"marginTop")}else if(m&&jQuery.boxModel){b+=a(e,"borderLeftWidth");f+=a(e,"borderTopWidth")}}else{do{k=d.css(g,"position");b+=g.offsetLeft;f+=g.offsetTop;if(l||m){b+=a(g,"borderLeftWidth");f+=a(g,"borderTopWidth");if(l&&k=="absolute")p=true;if(m&&k=="relative")q=true}k=g.offsetParent;if(c.scroll||l){do{if(c.scroll){j+=g.scrollLeft;
i+=g.scrollTop}if(l&&g!=e&&d.css(g,"overflow")!="visible"){b+=a(g,"borderLeftWidth");f+=a(g,"borderTopWidth")}g=g.parentNode}while(g!=k)}g=k;if(g.tagName.toLowerCase()=="body"||g.tagName.toLowerCase()=="html"){if((t||m&&d.boxModel)&&n!="absolute"&&n!="fixed"){b+=a(g,"marginLeft");f+=a(g,"marginTop")}if(l&&!p&&n!="fixed"||m&&n=="static"&&!q){b+=a(g,"borderLeftWidth");f+=a(g,"borderTopWidth")}break}}while(g)}b=o(e,c,b,f,j,i);if(h){d.extend(h,b);return this}else return b},offsetLite:function(c,h){var b=
0,f=0,j=0,i=0,e=this[0],g;c=d.extend({margin:true,border:false,padding:false,scroll:true},c||{});do{b+=e.offsetLeft;f+=e.offsetTop;g=e.offsetParent;if(c.scroll){do{j+=e.scrollLeft;i+=e.scrollTop;e=e.parentNode}while(e!=g)}e=g}while(e&&e.tagName.toLowerCase()!="body"&&e.tagName.toLowerCase()!="html");b=o(this[0],c,b,f,j,i);if(h){d.extend(h,b);return this}else return b}});var a=function(c,h){return parseInt(d.css(c.jquery?c[0]:c,h))||0},o=function(c,h,b,f,j,i){if(!h.margin){b-=a(c,"marginLeft");f-=
a(c,"marginTop")}if(h.border&&(d.browser.safari||d.browser.opera)){b+=a(c,"borderLeftWidth");f+=a(c,"borderTopWidth")}else if(!h.border&&!(d.browser.safari||d.browser.opera)){b-=a(c,"borderLeftWidth");f-=a(c,"borderTopWidth")}if(h.padding){b+=a(c,"paddingLeft");f+=a(c,"paddingTop")}if(h.scroll){j-=c.scrollLeft;i-=c.scrollTop}return h.scroll?{top:f-i,left:b-j,scrollTop:i,scrollLeft:j}:{top:f,left:b}}})(jQuery);
var RML=function(){var l=Array.prototype.slice,g=Object.prototype.toString,f="[object Array]",j="[object Function]",k="[object Object]";function n(a,b,d,c){var e=a[1];if(g.call(b)===f)b=b.join(c);switch(d){case 1:case true:a.push(" ",b,"/>");break;case 2:a.push(" ",b,">");break;default:a.push(">",b,"</",e,">")}return a.join("")}function o(a,b,d,c,e){var h=false,m=a[1],i;if(c.has(b,"content"))h=true;for(i in b)c.has(b,i)&&!c.filter[i]&&a.push(c.rsub(i,b[i]));switch(d){case 1:case true:a.push("/>");
break;case 2:a.push(">");break;default:a.push(">");if(h)switch(g.call(b.content)){case j:a.push(b.content());break;case f:a.push(b.content.join(e));break;default:a.push(b.content)}a.push("</",m,">")}return a.join("")}return{cache:function(a,b){this.cached[a]=this.compile(b)},cached:{},compile:function(a){return this.template(a)},filter:{content:true},has:function(a,b){return a&&a.hasOwnProperty&&a.hasOwnProperty(b)},iterate:function(a,b,d){var c,e=[],h=a.length||0;switch(g.call(a)){case f:if(d)for(c=
0;c<h;c++){d.content=a[c];e.push(RML.tag(b,d))}else for(c=0;c<h;c++)e.push(RML[b](a[c]));break;case k:for(c in a)this.has(a,c)&&e.push(RML[b](a[c]));break}return e.join("")},rsub:function(a,b){a=a.replace(/_/,"");var d=b?' %1="%2"':" %1";return b?d.replace("%1",a).replace("%2",b):d.replace("%1",a)},siblings:function(){var a=l.call(arguments,0);return a.join("")},strSub:function(a,b){return this.template(a,b)},tag:function(a,b,d,c){b=b||"";c=c||"";a=["<",a];return g.call(b)!==k?n(a,b,d,c):o(a,b,d,
this,c)},tags:{a:0,b:0,br:1,canvas:0,code:0,div:0,dl:0,dd:0,dt:0,em:0,form:0,h1:0,h2:0,h3:0,h4:0,hr:1,i:0,img:0,input:1,li:0,link:1,ol:0,p:0,pre:0,script:0,select:0,strong:0,span:0,table:0,tbody:0,td:0,textarea:0,th:0,thead:0,tr:0,ul:0},template:function(a,b){var d=g.call(a)===f?a.join(""):a;function c(e){return d.replace(/\$\{(.+?)\}/g,function(h,m){return e[m]})}return b?c(b):c}}}();
(function(){var l=RML.has,g=RML.tags,f;for(f in g)if(l(g,f))RML[f]=function(j){return function(k){return this.tag(j,k,this.tags[j])}}(f)})();

/*
 * jQuery Tooltip plugin 1.3
 *
 * http://bassistance.de/jquery-plugins/jquery-plugin-tooltip/
 * http://docs.jquery.com/Plugins/Tooltip
 *
 * Copyright (c) 2006 - 2008 Jörn Zaefferer
 *
 * $Id: jquery.tooltip.js 5741 2008-06-21 15:22:16Z joern.zaefferer $
 * 
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */
(function($){var helper={},current,title,tID,IE=$.browser.msie&&/MSIE\s(5\.5|6\.)/.test(navigator.userAgent),track=false;$.tooltip={blocked:false,defaults:{delay:200,fade:false,showURL:true,extraClass:"",top:15,left:15,id:"tooltip"},block:function(){$.tooltip.blocked=!$.tooltip.blocked;}};$.fn.extend({tooltip:function(settings){settings=$.extend({},$.tooltip.defaults,settings);createHelper(settings);return this.each(function(){$.data(this,"tooltip",settings);this.tOpacity=helper.parent.css("opacity");this.tooltipText=this.title;$(this).removeAttr("title");this.alt="";}).mouseover(save).mouseout(hide).click(hide);},fixPNG:IE?function(){return this.each(function(){var image=$(this).css('backgroundImage');if(image.match(/^url\(["']?(.*\.png)["']?\)$/i)){image=RegExp.$1;$(this).css({'backgroundImage':'none','filter':"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=crop, src='"+image+"')"}).each(function(){var position=$(this).css('position');if(position!='absolute'&&position!='relative')$(this).css('position','relative');});}});}:function(){return this;},unfixPNG:IE?function(){return this.each(function(){$(this).css({'filter':'',backgroundImage:''});});}:function(){return this;},hideWhenEmpty:function(){return this.each(function(){$(this)[$(this).html()?"show":"hide"]();});},url:function(){return this.attr('href')||this.attr('src');}});function createHelper(settings){if(helper.parent)return;helper.parent=$('<div id="'+settings.id+'"><h3></h3><div class="body"></div><div class="url"></div></div>').appendTo(document.body).hide();if($.fn.bgiframe)helper.parent.bgiframe();helper.title=$('h3',helper.parent);helper.body=$('div.body',helper.parent);helper.url=$('div.url',helper.parent);}function settings(element){return $.data(element,"tooltip");}function handle(event){if(settings(this).delay)tID=setTimeout(show,settings(this).delay);else
show();track=!!settings(this).track;$(document.body).bind('mousemove',update);update(event);}function save(){if($.tooltip.blocked||this==current||(!this.tooltipText&&!settings(this).bodyHandler))return;current=this;title=this.tooltipText;if(settings(this).bodyHandler){helper.title.hide();var bodyContent=settings(this).bodyHandler.call(this);if(bodyContent.nodeType||bodyContent.jquery){helper.body.empty().append(bodyContent)}else{helper.body.html(bodyContent);}helper.body.show();}else if(settings(this).showBody){var parts=title.split(settings(this).showBody);helper.title.html(parts.shift()).show();helper.body.empty();for(var i=0,part;(part=parts[i]);i++){if(i>0)helper.body.append("<br/>");helper.body.append(part);}helper.body.hideWhenEmpty();}else{helper.title.html(title).show();helper.body.hide();}if(settings(this).showURL&&$(this).url())helper.url.html($(this).url().replace('http://','')).show();else
helper.url.hide();helper.parent.addClass(settings(this).extraClass);if(settings(this).fixPNG)helper.parent.fixPNG();handle.apply(this,arguments);}function show(){tID=null;if((!IE||!$.fn.bgiframe)&&settings(current).fade){if(helper.parent.is(":animated"))helper.parent.stop().show().fadeTo(settings(current).fade,current.tOpacity);else
helper.parent.is(':visible')?helper.parent.fadeTo(settings(current).fade,current.tOpacity):helper.parent.fadeIn(settings(current).fade);}else{helper.parent.show();}update();}function update(event){if($.tooltip.blocked)return;if(event&&event.target.tagName=="OPTION"){return;}if(!track&&helper.parent.is(":visible")){$(document.body).unbind('mousemove',update)}if(current==null){$(document.body).unbind('mousemove',update);return;}helper.parent.removeClass("viewport-right").removeClass("viewport-bottom");var left=helper.parent[0].offsetLeft;var top=helper.parent[0].offsetTop;if(event){left=event.pageX+settings(current).left;top=event.pageY+settings(current).top;var right='auto';if(settings(current).positionLeft){right=$(window).width()-left;left='auto';}helper.parent.css({left:left,right:right,top:top});}var v=viewport(),h=helper.parent[0];if(v.x+v.cx<h.offsetLeft+h.offsetWidth){left-=h.offsetWidth+20+settings(current).left;helper.parent.css({left:left+'px'}).addClass("viewport-right");}if(v.y+v.cy<h.offsetTop+h.offsetHeight){top-=h.offsetHeight+20+settings(current).top;helper.parent.css({top:top+'px'}).addClass("viewport-bottom");}}function viewport(){return{x:$(window).scrollLeft(),y:$(window).scrollTop(),cx:$(window).width(),cy:$(window).height()};}function hide(event){if($.tooltip.blocked)return;if(tID)clearTimeout(tID);current=null;var tsettings=settings(this);function complete(){helper.parent.removeClass(tsettings.extraClass).hide().css("opacity","");}if((!IE||!$.fn.bgiframe)&&tsettings.fade){if(helper.parent.is(':animated'))helper.parent.stop().fadeTo(tsettings.fade,0,complete);else
helper.parent.stop().fadeOut(tsettings.fade,complete);}else
complete();if(settings(this).fixPNG)helper.parent.unfixPNG();}})(jQuery);
/*
 * jQuery delegate plug-in v1.0
 *
 * Copyright (c) 2007 Jörn Zaefferer
 *
 * $Id: jquery.delegate.js 4786 2008-02-19 20:02:34Z joern.zaefferer $
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */
(function(a){a.each({focus:"focusin",blur:"focusout"},function(c,b){a.event.special[b]={setup:function(){if(a.browser.msie)return false;this.addEventListener(c,a.event.special[b].handler,true)},teardown:function(){if(a.browser.msie)return false;this.removeEventListener(c,a.event.special[b].handler,true)},handler:function(d){arguments[0]=a.event.fix(d);arguments[0].type=b;return a.event.handle.apply(this,arguments)}}});a.extend(a.fn,{delegate:function(c,b,d){return this.bind(c,function(f){var e=a(f.target);
	if(e.is(b))return d.apply(e,arguments)})},triggerEvent:function(c,b){return this.triggerHandler(c,[jQuery.event.fix({type:c,target:b})])}})})(jQuery);
// Our scripts
I.provide("base.awesome");base.awesome.hello=function(){return"Also, base.awesome namespace exists and is ready for use."};
I.provide("base.test");
$(document).ready(function(){base.test.tooltips=function(){this.show('So, mouse over the "What\'s this for? thing"');$("#hovered").tooltip({bodyHandler:function(){return RML.p("ITS FOR A TOOLTIP!!!")},showURL:!1})};base.test.show=function(b){var a=$("#ta_output");curr_val=[a.val()];curr_val.push(b);a.val(curr_val.join("\n"))};base.test.show("jQuery, plugins and RML are loaded and parsed now");base.test.show(base.awesome.hello());$("#btn_tt").click(function(){base.test.show("All dependencies are loaded and parsed");base.test.tooltips()})});
